/// Flutter icons Circles
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Circles
///      fonts:
///       - asset: fonts/Circles.ttf
///
/// 
/// * Font Awesome, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class Circles {
  Circles._();

  static const _kFontFam = 'Circles';

  static const IconData circle_empty = IconData(0xf10c, fontFamily: _kFontFam);
  static const IconData circle = IconData(0xf111, fontFamily: _kFontFam);
}
