/// Flutter icons MainIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MainIcons
///      fonts:
///       - asset: fonts/MainIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class MainIcons {
  MainIcons._();

  static const _kFontFam = 'MainIcons';

  static const IconData run = IconData(0xe800, fontFamily: _kFontFam);
  static const IconData calories = IconData(0xe801, fontFamily: _kFontFam);
  static const IconData coin = IconData(0xe802, fontFamily: _kFontFam);
  static const IconData distance = IconData(0xe803, fontFamily: _kFontFam);
  static const IconData menu = IconData(0xe804, fontFamily: _kFontFam);
  static const IconData pen = IconData(0xe805, fontFamily: _kFontFam);
  static const IconData speed = IconData(0xe806, fontFamily: _kFontFam);
  static const IconData time = IconData(0xe807, fontFamily: _kFontFam);
}
